import jsPDF from 'jspdf'
import 'jspdf-autotable'

export function generateQuotationPDF(deal: any, tenant: any) {
  const doc = new jsPDF() as any

  // 1. Branding & Header
  doc.setFontSize(22)
  doc.setTextColor(99, 102, 241) // Indigo Primary
  doc.text(tenant.name || 'MultiCRM Pro', 20, 25)
  
  doc.setFontSize(10)
  doc.setTextColor(100)
  doc.text('GSTIN: ' + (tenant.settings?.taxId || 'N/A'), 20, 32)
  doc.text('Web: ' + (tenant.domain || 'www.multicrm.pro'), 20, 38)

  doc.setFontSize(28)
  doc.setTextColor(230)
  doc.text('QUOTATION', 140, 28)

  // 2. Info Block
  doc.setDrawColor(230)
  doc.line(20, 45, 190, 45)

  doc.setFontSize(12)
  doc.setTextColor(0)
  doc.setFont('helvetica', 'bold')
  doc.text('Customer Details:', 20, 55)
  doc.setFont('helvetica', 'normal')
  doc.text(`${deal.contact?.firstName} ${deal.contact?.lastName}`, 20, 62)
  doc.text(deal.contact?.company || 'Individual', 20, 68)
  doc.text(deal.contact?.email || '', 20, 74)

  doc.setFont('helvetica', 'bold')
  doc.text('Quotation Info:', 130, 55)
  doc.setFont('helvetica', 'normal')
  doc.text(`Reference: QT-${deal.id.slice(-6).toUpperCase()}`, 130, 62)
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 130, 68)
  doc.text(`Valid Until: ${new Date(Date.now() + 15 * 86400000).toLocaleDateString()}`, 130, 74)

  // 3. Line Items table
  const tableData = deal.products?.length > 0 
    ? deal.products.map((p: any) => [
        p.product.name,
        p.quantity.toString(),
        p.price.toLocaleString(),
        p.discount + '%',
        p.total.toLocaleString()
      ])
    : [[deal.title, '1', deal.value.toLocaleString(), '0%', deal.value.toLocaleString()]]

  doc.autoTable({
    startY: 85,
    head: [['Product/Service', 'Qty', 'Unit Price', 'Disc', 'Total']],
    body: tableData,
    styles: { fontSize: 10, cellPadding: 6 },
    headStyles: { fillColor: [99, 102, 241], textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [249, 250, 251] },
  })

  // 4. Totals
  const finalY = (doc as any).lastAutoTable.cursor.y + 10
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Total Amount:', 130, finalY)
  doc.setTextColor(99, 102, 241)
  doc.text(`${deal.currency || 'INR'} ${deal.value.toLocaleString()}`, 165, finalY)

  // 5. Terms
  doc.setFontSize(10)
  doc.setTextColor(150)
  doc.text('Terms & Conditions:', 20, finalY + 20)
  doc.setFontSize(8)
  doc.text('- Payment due within 15 days of quotation.', 20, finalY + 26)
  doc.text('- Valid for limited time as per header date.', 20, finalY + 31)
  doc.text('- This is a system-generated document and does not require a physical signature.', 20, finalY + 36)

  // 6. Footer
  doc.setFontSize(9)
  doc.setTextColor(180)
  doc.text(`Generated by ${tenant.name} MultiCRM Pro`, 105, 285, { align: 'center' })

  doc.save(`Quotation_${deal.id.slice(-6).toUpperCase()}.pdf`)
}
